server:
  servlet:
    context-path: /ecovias/api
  port: 8081

spring:
  data:
    mongodb:
      database: ecovias_db
      uri: mongodb://localhost:27017/

info:
  build:
    version: ${version?:unknown}