version: '3'
services:
  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - ecoviasnetwork

  rules:
    image: ecovias-service:v0.0.1
    container_name: ecovias-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8081:8081"
    networks:
      - ecoviasnetwork
    depends_on:
      - "mongo"

networks:
  ecoviasnetwork:
    driver: bridge

volumes:
  mongo_data: